//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_adonet.LoginAndRegistrate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginAndRegistrate.ILoginRegisterUser")]
    public interface ILoginRegisterUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegisterUser/CheckUserOnDB", ReplyAction="http://tempuri.org/ILoginRegisterUser/CheckUserOnDBResponse")]
        bool CheckUserOnDB(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegisterUser/CheckUserOnDB", ReplyAction="http://tempuri.org/ILoginRegisterUser/CheckUserOnDBResponse")]
        System.Threading.Tasks.Task<bool> CheckUserOnDBAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegisterUser/AddNewUserOnDB", ReplyAction="http://tempuri.org/ILoginRegisterUser/AddNewUserOnDBResponse")]
        void AddNewUserOnDB(string login, int age, string password, int gender, byte[] usrImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegisterUser/AddNewUserOnDB", ReplyAction="http://tempuri.org/ILoginRegisterUser/AddNewUserOnDBResponse")]
        System.Threading.Tasks.Task AddNewUserOnDBAsync(string login, int age, string password, int gender, byte[] usrImage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginRegisterUserChannel : Kurs_adonet.LoginAndRegistrate.ILoginRegisterUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginRegisterUserClient : System.ServiceModel.ClientBase<Kurs_adonet.LoginAndRegistrate.ILoginRegisterUser>, Kurs_adonet.LoginAndRegistrate.ILoginRegisterUser {
        
        public LoginRegisterUserClient() {
        }
        
        public LoginRegisterUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginRegisterUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegisterUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegisterUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckUserOnDB(string login, string password) {
            return base.Channel.CheckUserOnDB(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserOnDBAsync(string login, string password) {
            return base.Channel.CheckUserOnDBAsync(login, password);
        }
        
        public void AddNewUserOnDB(string login, int age, string password, int gender, byte[] usrImage) {
            base.Channel.AddNewUserOnDB(login, age, password, gender, usrImage);
        }
        
        public System.Threading.Tasks.Task AddNewUserOnDBAsync(string login, int age, string password, int gender, byte[] usrImage) {
            return base.Channel.AddNewUserOnDBAsync(login, age, password, gender, usrImage);
        }
    }
}
